### ISSUE TITLE
Script error when trying to find or directly download YouTube files.

### ISSUE THREAD

**Issue by rpcjacobs** [kacso/JumpToFile---MediaMonkey#1]
The script reported errors on lines 946 or 949 on column 2, but i didn't have any logs. I've fiddled with script a bit and fixed it for my installation. Ended up using the shortname for `Program Files (x86)` even though that might not even have been needed.

```
c:/PROGRA~2/MediaMonkey/Scripts/Auto/youtube-dl.exe
```

In any case, i used the shortname to be sure it could find the file. Probably because my Windows Account (username) has a space (first and lastname), which probably gave problems for `%appdata%`.

I've never programmed before with VBS, but i think there might be an issue using the command without surrounding quotes. And if you did account for that, they might not be working as intended!

Optionally, you could also use [another program files env variable](http://stackoverflow.com/questions/9594066/how-to-get-program-files-x86-env-variable)

Just my 2c's!

Lats but not least, thanks for your efforts. It's a great addition to MediaMonkey! 

_p.s. Started first by manually creating the temp folder structure, which didnt do the trick. You might also want to add some check for it to exist, and check permissions. Or even better, move it to an already existing temp windows dir._

My fixed version: https://gist.github.com/12roar/5d33b5e925fb4f53990b#file-jumptofileauto-vbs

**Comment by kacso** [comment]
Hi,
First thank you for your feedback and thanks for using the script.

I'll take a better look in those issues ASAP. On first, it seams that it could be problem only because of spaces in username (I didn't count on that, but adding quotes in path should resolve problems). It's really weird to me that it works for you by using  "PROGRA-2" because, if you installed it using mmip file, script should be installed in "%appdata%/MediaMonkey/Scripts/Auto/", not in Program files directory (There are permission problems if installed in Program files).
For the temp folder structure, script should create folder structure by it's own (I have tested it right now and it worked for me).

This feature (Youtube download), was tested on Windows 10, I will test it on Win 7 too.

Again, thanks for feedback.

**Comment by kacso** [comment]
Hi again,
I'm glad to say that I manage to solve your problem and from now on there should no be such errors because of spaces in the username (tested on Win7 & Win10). Updated version is here and also on Mediamonkey official site.

Just to remained you, script should be installed to %appData%/Roaming/MediaMonkey/Scripts/Auto,  not in Program Files folder (This is done by default if using mmip installer) because of privileges problem of Program Files folder (You can't write anything without Administrator permissions).
